### ISSUE TITLE
Statystyki nie działają

### ISSUE THREAD

**Issue by konik32** [maniekstasz/OfferSeeker#27]
Nie wyświetlają się statystyki, pobiera je ale ich nie widać.

**Comment by rampler** [comment]
U mnie działają. Jakieś większe info jak odświeżyć błąd? I skąd wiesz, że
pobiera, a tylko nie wyświetla?
21 lis 2014 01:42 "konik32" notifications@github.com napisał(a):

**Comment by rampler** [comment]
Sprawdzam na bazie otrzymanej z fb i mianowicie po pierwsze nie ma z niej żadnych ofert. Jak nie ma żadnych ofert to nie można kliknąć Tak/Nie przez co nie ma też statystyk. Statystyki odnoszą się do aktywności użytkownika i ile razy kliknął Tak/Nie, a nie do ilość ogłoszeń ogólnie.

Ponadto wywala mi wyjątek:
2014-11-21 07:41:35.109  INFO 7676 --- [pool-2-thread-1] o.s.b.c.l.support.SimpleJobLauncher      : Job: [SimpleJob: [name=processPossibleOffers]] launched with the following parameters: [{lastJobDate=1416552043017}]
2014-11-21 07:41:35.151  INFO 7676 --- [pool-2-thread-1] o.s.batch.core.job.SimpleStepHandler     : Executing step: [possibleOfferProcessingStep]
Hibernate: select count(possibleof0_.id) as col_0_0_ from possible_offers_links possibleof0_ where possibleof0_.timestamp>?
Hibernate: select possibleof0_.id as id1_2_, possibleof0_.timestamp as timestam2_2_, possibleof0_.url as url3_2_ from possible_offers_links possibleof0_ where possibleof0_.timestamp>? order by possibleof0_.timestamp desc limit ?
2014-11-21 07:41:35.339 ERROR 7676 --- [pool-2-thread-1] o.s.batch.core.step.AbstractStep         : Encountered an error executing step possibleOfferProcessingStep in job processPossibleOffers

java.lang.ArrayIndexOutOfBoundsException: 0
    at libsvm.svm.svm_group_classes(svm.java:1914)
    at libsvm.svm.svm_train(svm.java:1992)
    at pl.edu.agh.offerseeker.analysing.SVM.train(SVM.java:69)
    at pl.edu.agh.offerseeker.service.SVMPageProcessor.processPage(SVMPageProcessor.java:75)
    at pl.edu.agh.offerseeker.job.PossibleOfferProcessor.process(PossibleOfferProcessor.java:26)
    at pl.edu.agh.offerseeker.job.PossibleOfferProcessor.process(PossibleOfferProcessor.java:19)

**Comment by bambalooon** [comment]
Ten błąd wyskakuje jak w {user.dir}/offer_seeker/db nie ma plików do treningu PageProcessora, nie ma z czego się z czego uczyć i wywala IndexOutOfBounds..

**Comment by konik32** [comment]
Jedyne co usunąłem z folderu db to te pliki umieszcone w orig, ale sprawdzałem i u mnie działało normalnie.

**Comment by rampler** [comment]
Ok znalazłem błąd - baza jest ok - źle przekopiowałem.
A błąd z statystykami polegał na tym, że jeżeli jest jeden dzień to nie rysuje lini, ponieważ puktStartowy = punktKońcowy i nie widać go wtedy. Wystarczy, że dziś odpaliłem i automatycznie pokazuje się linia pomiędzy dniami. Jakby nie patrzeć w sumie to błędem nie jest tylko za wąskim zakresem przeszukiwań.
Mogę spróbować to zmienić, jak chcecie, ale czy jest sens?(rozszerzyłbym o jeden dzień do tyłu i jeżeli nie byłoby głosów to po prostu wyrysuje linię od 0 poprzedniego dnia do aktualnej wartości dzisiejszego dnia).
Starać się to jakoś naprawić, czy olewamy to, a baza będzie miała statystyki z min. dwóch dni?
